version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: seed-bin-mongodb
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=seed-bin-management
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

volumes:
  mongodb_data: 